do not call logging or raise SystemExit from within the python shutdown path
running this python3 script

import logging
class TestEnv:
   def __init__(self):
      logging.basicConfig(filename="logfile.log",level=logging.DEBUG, format='%(asctime)s %(message)s')
      logging.info("called __init__")
   def __del__(self):
      print("TestEnv.__del__")
      logging.info("called __del__")
te = TestEnv()

results in this ignored exception:

TestEnv.__del__
Exception ignored in: <function TestEnv.__del__ at 0x7fe3d047db70>
Traceback (most recent call last):
  File "/tmp/foo.py", line 8, in __del__
  File "/usr/lib/python3.7/logging/__init__.py", line 1994, in info
  File "/usr/lib/python3.7/logging/__init__.py", line 1383, in info
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined

'logging' is no longer usable because python is shutting down and some
modules are no longer available

calling sys.exit() (i.e. raising SystemExit) will just report more
ignored exceptions